version: "3.8"

services:
  app:
    build: .
    container_name: app
    volumes:
      - ./:/app
    environment:
      - name=value
    ports:
      - "5000:5000"
    networks:
      - my_network
  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=app #schema name
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db_data:/var/lib/mysql
      # - ./path/to/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - my_network

  redis:
    container_name: redis_db
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - my_network


volumes:
  db_data:

networks:
  my_network:
    driver: bridge